### ISSUE TITLE
Addendum still present even after editing answers away

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-MLHResponseToMotionRegardingSupport#1]
Likely I'm using the ALDocument wrong somehow, but idk.

* make an answer with agreed on how much -> true, para 6 -> true, and exactly -> false, with some reasons for not exactly, then edit the answers to be para 6 -> false, and para 7 -> true. The `overflow_fields` properly are false and don't show up in the document, but the addendum itself is still there, even though there's nothing in it.

Try to look more into stuff with the ALDocument addendum, make an issue there if I can't figure it out.

**Comment by ekressmiller** [comment]
Changed addendum method and this is no longer an issue. Tested scenario above and it works.
